# Generated by Django 5.1 on 2024-08-15 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classperiod', '0001_initial'),
        ('course', '0001_initial'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_period',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='class_period',
            name='student_class',
        ),
        migrations.AddField(
            model_name='class_period',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_periods', to='student.student'),
        ),
        migrations.AddField(
            model_name='class_period',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_periods', to='teacher.teacher'),
        ),
        migrations.AlterField(
            model_name='class_period',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_periods', to='course.courses'),
        ),
        migrations.AlterField(
            model_name='class_period',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='class_period',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
